services:
  - type: web
    name: eden-core-physics-game
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
